# name: Performance tests

# # Controls when the action will run. Triggers the workflow on push or pull request
# # events but only for the master branch
# on:
#   workflow_dispatch:
#       inputs:
#         logLevel:
#           description: 'Log level'
#           required: true
#           default: 'warning'
#           type: choice
#           options:
#           - info
#           - warning
#           - debug
#         # tags:
#         #   description: 'Tags para os cenarios de teste'
#         #   required: false
#         #   type: boolean
#         environment:
#           description: 'Ambiente para executar os testes'
#           type: choice
#           options:
#             - main
#           required: true

#   # schedule:
#   #   # * is a special character in YAML so you have to quote this string
#   #   - cron: '0 9 * * *'

# jobs:
#   K6_Testing:
#     name: k6 docker test run on Ubuntu
#     runs-on: ubuntu-latest
#     container:
#       image: docker://loadimpact/k6:latest
#       options: --user 1001

#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - name: Checkout
#         uses: actions/checkout@v3

#       # Setup nodejs
#       - name: cache node modules
#         uses: actions/cache@v3
#         with:
#           path: ~/.npm
#           key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
#           restore-keys: |
#             ${{ runner.os }}-build-${{ env.cache-name }}-
#             ${{ runner.os }}-build-
#             ${{ runner.os }}-

#       # Run k6 tests
#       - run: |
#           echo "Executando teste - 8000vu"
#           echo "Log level: $LEVEL"
#           echo "Tags: $TAGS"
#           echo "Environment: $ENVIRONMENT"
#           k6 run src/ppi-carga-leve.js

#         env:
#           LEVEL: ${{ inputs.logLevel }}
#           TAGS: ${{ inputs.tags }}
#           ENVIRONMENT: ${{ inputs.environment }}

#      # Upload performance test results
#       - name: Upload performance test results
#         uses: actions/upload-artifact@v3
#         with:
#           name: k6-report
#           path: |
#             tests/reports/summary.json
#             tests/reports/fullFlowLoad.html
